### ISSUE TITLE
Where can I find Version 1.2.4?

### ISSUE THREAD

**Issue by aheissenberger** [leap-spark/ferret#1]
which is the plublished version on WP:
https://wordpress.org/plugins/ferret/

**Comment by NeonArray** [comment]
Sorry for a really long delay @aheissenberger, for some reason I was never notified of this issue. I don't have the repositories mirrored automatically, and simply just forgot to update the Github version.

I'm sure you've probably moved onto a different solution by now, but I am going to make it a point tomorrow to ensure that this repo and the WordPress directory one, are synced up automatically.

**Comment by NeonArray** [comment]
Updated to 1.2.4
